name: Deploy with self-hosted runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Checkout mã nguồn
      - name: Checkout mã nguồn
        uses: actions/checkout@v3

      # Copy file .env file
      - name: Copy file .env file
        run: |
          echo "SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}" >> .env
          echo "SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "SA_PASSWORD=${{ secrets.SA_PASSWORD }}" >> .env

      # Build và Deploy Docker
      - name: Build and Deploy Docker
        run: |
          sudo docker-compose down -d --build
          sudo docker-compose up -d --build
